### ISSUE TITLE
Crash when get closeto big quartz house

### ISSUE THREAD

**Issue by CatAndHorse** [Darkosto/InvasionIssues#231]
May caused by a data broken mob mobSpawner

-- Head --
Thread: Server thread
Stacktrace:
	at org.spongepowered.common.registry.type.entity.EntityTypeRegistryModule.getForClass(EntityTypeRegistryModule.java:231)
	at net.minecraft.tileentity.MobSpawnerBaseLogic.readEntityFromCompoundAtWorld(MobSpawnerBaseLogic.java:602)
	at net.minecraft.tileentity.MobSpawnerBaseLogic.redirect$onConstruct$zii000(MobSpawnerBaseLogic.java:582)
	at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98278_g(MobSpawnerBaseLogic.java:102)
	at net.minecraft.tileentity.TileEntityMobSpawner.func_73660_a(SourceFile:90)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:226)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2803)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2790)

-- Block entity being ticked --
Details:
	Name: MobSpawner // net.minecraft.tileentity.TileEntityMobSpawner
	Block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (320,88,-320), Chunk: (at 0,5,0 in 20,-20; contains blocks 320,0,-320 to 335,255,-305), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6003)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157)

**Comment by GenDeathrow** [comment]
Report this to sponge... this doesn't happen in forge.
