### ISSUE TITLE
Creative Page 3 still crashes after recent update.

### ISSUE THREAD

**Issue by RussianSanity** [Darkosto/InvasionIssues#57]
Just checked with the recent update, the creative tab  page 3 still causes the crash. Just to let you know.

// Don't do that.

Time: 3/31/17 6:38 AM
Description: Rendering screen

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at com.rwtema.extrautils2.compatibility.MyCreativeTabs.func_78016_d(MyCreativeTabs.java:27)
	at net.minecraft.creativetab.CreativeTabs.func_151244_d(CreativeTabs.java:178)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:866)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:703)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Darkosto** [comment]
This wasn't fixed in the update. I'm aware of this issue as it's been reported before.

**Comment by ReiannaWinters** [comment]
Any idea when this might be fixed? Since it crashes on page 3 I cant get to 4-9 either

**Comment by ReiannaWinters** [comment]
https://pastebin.com/3nZCKXC7

My Crash

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/InvasionIssues/issues/14#issuecomment-298188374
